'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditType
    Public Property ID As Integer
    Public Property AuditType1 As String

    Public Overridable Property Audit As ICollection(Of Audit) = New HashSet(Of Audit)

End Class
