'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Audit
    Public Property ID As Integer
    Public Property AuditType As Nullable(Of Integer)
    Public Property AuditTitle As String
    Public Property AuditDetails As String
    Public Property ClientID As Nullable(Of Integer)
    Public Property AuditDate As Nullable(Of Date)
    Public Property AuditUser As String

    Public Overridable Property AuditType1 As AuditType
    Public Overridable Property client_Profile As client_Profile

End Class
