'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Notes
    Public Property ID As Integer
    Public Property NoteLabel As String
    Public Property NoteText As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateAdded As Nullable(Of Date)
    Public Property ClientID As Integer

    Public Overridable Property client_Profile As client_Profile

End Class
