'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_ContactTracing
    Public Property ID As Integer
    Public Property FromDate As Nullable(Of Date)
    Public Property ToDate As Nullable(Of Date)
    Public Property LastContact As Nullable(Of Date)
    Public Property ContactTypeID As Nullable(Of Integer)
    Public Property ReasonTypeID As Nullable(Of Integer)
    Public Property RelationshipID As Nullable(Of Integer)
    Public Property CommunityID As Nullable(Of Integer)
    Public Property DiagnosisID As Nullable(Of Integer)
    Public Property PriorityID As Nullable(Of Integer)
    Public Property Comments As String
    Public Property ClientID As Nullable(Of Integer)
    Public Property ContactClientID As Nullable(Of Integer)
    Public Property Active As Boolean

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property client_Profile1 As client_Profile
    Public Overridable Property common_Community As common_Community
    Public Overridable Property common_ContactPriority As common_ContactPriority
    Public Overridable Property common_ContactReason As common_ContactReason
    Public Overridable Property common_ContactType As common_ContactType
    Public Overridable Property client_Outcome As client_Outcome
    Public Overridable Property common_ContactRelationship As common_ContactRelationship

End Class
