'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Communication
    Public Property ID As Integer
    Public Property CommunicationDateTime As Nullable(Of Date)
    Public Property MethodID As Nullable(Of Integer)
    Public Property ReasonID As Nullable(Of Integer)
    Public Property ContactedBy As Nullable(Of Integer)
    Public Property Comments As String
    Public Property ClientID As Integer
    Public Property ResultID As Nullable(Of Integer)
    Public Property ContactedByName As String

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_CommunicationMethod As common_CommunicationMethod
    Public Overridable Property common_CommunicationReason As common_CommunicationReason
    Public Overridable Property common_CommunicationResult As common_CommunicationResult
    Public Overridable Property common_TBUser As common_TBUser

End Class
