'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Profile
    Public Property ID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property LastUpdate As Nullable(Of Date)
    Public Property LastStatus As Nullable(Of Integer)
    Public Property StatusID As Nullable(Of Integer)
    Public Property Employee As Nullable(Of Boolean)
    Public Property Confirmed As Nullable(Of Boolean)

    Public Overridable Property client_BCG As ICollection(Of client_BCG) = New HashSet(Of client_BCG)
    Public Overridable Property client_Bloodwork As ICollection(Of client_Bloodwork) = New HashSet(Of client_Bloodwork)
    Public Overridable Property client_ContactNote As ICollection(Of client_ContactNote) = New HashSet(Of client_ContactNote)
    Public Overridable Property client_Demographic As ICollection(Of client_Demographic) = New HashSet(Of client_Demographic)
    Public Overridable Property client_IGRA As ICollection(Of client_IGRA) = New HashSet(Of client_IGRA)
    Public Overridable Property client_Investigation As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_RiskFactors As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_SkinTest As ICollection(Of client_SkinTest) = New HashSet(Of client_SkinTest)
    Public Overridable Property client_Sputum As ICollection(Of client_Sputum) = New HashSet(Of client_Sputum)
    Public Overridable Property client_Symptoms As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Xray As ICollection(Of client_Xray) = New HashSet(Of client_Xray)
    Public Overridable Property clinic_TBClinicAppointments As ICollection(Of clinic_TBClinicAppointments) = New HashSet(Of clinic_TBClinicAppointments)
    Public Overridable Property client_DiagnosticImage As ICollection(Of client_DiagnosticImage) = New HashSet(Of client_DiagnosticImage)
    Public Overridable Property client_Communication As ICollection(Of client_Communication) = New HashSet(Of client_Communication)
    Public Overridable Property client_CommunicationBulletin As ICollection(Of client_CommunicationBulletin) = New HashSet(Of client_CommunicationBulletin)
    Public Overridable Property client_Document As ICollection(Of client_Document) = New HashSet(Of client_Document)
    Public Overridable Property client_Followup As ICollection(Of client_Followup) = New HashSet(Of client_Followup)
    Public Overridable Property client_Notes As ICollection(Of client_Notes) = New HashSet(Of client_Notes)
    Public Overridable Property client_ContactTracing As ICollection(Of client_ContactTracing) = New HashSet(Of client_ContactTracing)
    Public Overridable Property client_ContactTracing1 As ICollection(Of client_ContactTracing) = New HashSet(Of client_ContactTracing)
    Public Overridable Property common_Status As common_Status
    Public Overridable Property Audit As ICollection(Of Audit) = New HashSet(Of Audit)
    Public Overridable Property client_Outcome As ICollection(Of client_Outcome) = New HashSet(Of client_Outcome)

End Class
