'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_OutcomeTreatmentRegimen
    Public Property ID As Integer
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Doseage As String
    Public Property NumberDoses As String
    Public Property Active As Nullable(Of Boolean)
    Public Property OutcomeID As Nullable(Of Integer)
    Public Property StatusID As Nullable(Of Integer)
    Public Property Notes As String
    Public Property FrequencyID As Nullable(Of Integer)
    Public Property MedicationID As Nullable(Of Integer)

    Public Overridable Property client_Outcome As client_Outcome
    Public Overridable Property common_Medication As common_Medication
    Public Overridable Property common_MedicationFrequency As common_MedicationFrequency
    Public Overridable Property common_MedicationStatus As common_MedicationStatus

End Class
