'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Outcome
    Public Property ID As Integer
    Public Property Outcome As Nullable(Of Integer)
    Public Property OutcomeDeterminationDate As Nullable(Of Date)
    Public Property Comments As String
    Public Property TBType As Nullable(Of Integer)
    Public Property ClientID As Nullable(Of Integer)
    Public Property DeterminedByID As Nullable(Of Integer)
    Public Property TreatmentID As Nullable(Of Integer)
    Public Property TransferDestination As String
    Public Property ClientDeathTBCause As Boolean
    Public Property ClientDeathTBContribute As Boolean
    Public Property ClientDeathTBNoContribute As Boolean
    Public Property ClientDeathDate As Nullable(Of Date)

    Public Overridable Property client_ContactTracing As ICollection(Of client_ContactTracing) = New HashSet(Of client_ContactTracing)
    Public Overridable Property client_OutcomeTreatment As client_OutcomeTreatment
    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_TBOutcome As common_TBOutcome
    Public Overridable Property common_TBTypes As common_TBTypes
    Public Overridable Property common_Clinicians As common_Clinicians
    Public Overridable Property client_OutcomeTreatmentRegimen As ICollection(Of client_OutcomeTreatmentRegimen) = New HashSet(Of client_OutcomeTreatmentRegimen)

End Class
