'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_RiskFactors
    Public Property ID As Integer
    Public Property InterviewByID As Integer
    Public Property InterviewDate As Date
    Public Property FamilyHistory As String
    Public Property ContactActiveTB2Yrs As Nullable(Of Integer)
    Public Property ContactActiveTB2YrsNotes As String
    Public Property DiabetesMellitusType1or2 As Nullable(Of Integer)
    Public Property DiabetesMellitusType1or2Notes As String
    Public Property EndStageRenalDisease As Nullable(Of Integer)
    Public Property EndStageRenalDiseaseNotes As String
    Public Property UnderlyingMedicalonditions As Nullable(Of Integer)
    Public Property UnderlyingMedicalonditionsNotes As String
    Public Property Homeless As Nullable(Of Integer)
    Public Property HomelessNotes As String
    Public Property OverCrowdedHousing As Nullable(Of Integer)
    Public Property OverCrowdedHousingNotes As String
    Public Property CorrectionalFacilityAtTimeDiag As Nullable(Of Integer)
    Public Property CorrectionalFacilityAtTimeDiagNotes As String
    Public Property PreviousAbnormalChestXray As Nullable(Of Integer)
    Public Property PreviousAbnormalChestXrayNotes As String
    Public Property SubstanceAbuse As Nullable(Of Integer)
    Public Property SubstanceAbuseNotes As String
    Public Property TobaccoSmoker As Nullable(Of Integer)
    Public Property TobaccoSmokerNotes As String
    Public Property TransplantRelatedImmunosuppression As Nullable(Of Integer)
    Public Property TransplantRelatedImmunosuppressionNotes As String
    Public Property HIV As Nullable(Of Integer)
    Public Property HIVNotes As String
    Public Property AIDS As Nullable(Of Integer)
    Public Property AIDSNotes As String
    Public Property Cancer As Nullable(Of Integer)
    Public Property CancerNotes As String
    Public Property ImmunosuppressiveDrugs As Nullable(Of Integer)
    Public Property ImmunosuppressiveDrugsNotes As String
    Public Property TravelHighIncidenceCountry2yrs As Nullable(Of Integer)
    Public Property TravelHighIncidenceCountry2yrsNotes As String
    Public Property AgeWhenInfectedLessThanEqual5yrs As Nullable(Of Integer)
    Public Property AgeWhenInfectedLessThanEqual5yrsNotes As String
    Public Property InactiveDiseaseNotAdequatelyTreated As Nullable(Of Integer)
    Public Property InactiveDiseaseNotAdequatelyTreatedNotes As String
    Public Property LTBIRrefusedDOP As Nullable(Of Integer)
    Public Property LTBIRrefusedDOPNotes As String
    Public Property ClientID As Integer
    Public Property CannabisUser As Nullable(Of Integer)
    Public Property CannabisNotes As String
    Public Property SmokingDeviceUse As Nullable(Of Integer)
    Public Property SmokingDeviceNotes As String
    Public Property TravelInuitNunaGutPrev2Years As Nullable(Of Integer)
    Public Property TravelInuitNunaGutPrev2YearsNotes As String
    Public Property VisitorsFrHighIncidenceRegion As Nullable(Of Integer)
    Public Property VisitorsFrHighIncidenceRegionNotes As String
    Public Property NotEligibleForTreatment As Nullable(Of Integer)
    Public Property NotEligibleForTreatmentNotes As String

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_Clinicians As common_Clinicians
    Public Overridable Property common_YesNoUnknownRefused As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused1 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused2 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused3 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused4 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused5 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused6 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused7 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused8 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused9 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused10 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused11 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused12 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused13 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused14 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused15 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused16 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused17 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused18 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused111 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused131 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused141 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused151 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused161 As common_YesNoUnknownRefused

End Class
