'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_IGRA
    Public Property ID As Integer
    Public Property ResultID As Nullable(Of Integer)
    Public Property CollectionDate As Nullable(Of Date)
    Public Property ResultDate As Nullable(Of Date)
    Public Property Comments As String
    Public Property ReasonForTestingID As Nullable(Of Integer)
    Public Property ReasonForTestingOther As String
    Public Property CollectedByID As Nullable(Of Integer)
    Public Property ClientID As Nullable(Of Integer)

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_IGRAResult As common_IGRAResult
    Public Overridable Property common_TBUser As common_TBUser
    Public Overridable Property common_TestReason As common_TestReason

End Class
