'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_SkinTest
    Public Property ID As Integer
    Public Property DateRead As Nullable(Of Date)
    Public Property DatePlaced As Nullable(Of Date)
    Public Property Comments As String
    Public Property CommentsResult As String
    Public Property RouteID As Nullable(Of Integer)
    Public Property Iduration As String
    Public Property LotID As Nullable(Of Integer)
    Public Property ProductID As Nullable(Of Integer)
    Public Property AdministeredByID As Nullable(Of Integer)
    Public Property SiteAdministered As Nullable(Of Integer)
    Public Property SiteAdministeredOther As String
    Public Property SiteRead As Nullable(Of Integer)
    Public Property ResultID As Nullable(Of Integer)
    Public Property ReadBy As Nullable(Of Integer)
    Public Property InjectionSiteID As Nullable(Of Integer)
    Public Property XrayRecommended As Nullable(Of Boolean)
    Public Property IGRARecommended As Nullable(Of Boolean)
    Public Property ConsentFactSheetProvided As Nullable(Of Boolean)
    Public Property ConsentFactSheetProvidedNo As Nullable(Of Boolean)
    Public Property ConsentBenefitsRisksUnderstood As Nullable(Of Boolean)
    Public Property ConsentBenefitsRisksUnderstoodNo As Nullable(Of Boolean)
    Public Property Return4872Hours As Nullable(Of Boolean)
    Public Property Return4872HoursNo As Nullable(Of Boolean)
    Public Property ConsentDate As Nullable(Of Date)
    Public Property FollowUpTestRequired As Nullable(Of Boolean)
    Public Property FollowUpTestNotRequired As Nullable(Of Boolean)
    Public Property FollowUpDate As Nullable(Of Date)
    Public Property TestReasonID As Nullable(Of Integer)
    Public Property TestReasonOther As String
    Public Property ClientID As Nullable(Of Integer)
    Public Property PlacedBy As Nullable(Of Integer)
    Public Property Dose As String
    Public Property SiteID As Nullable(Of Integer)
    Public Property SiteOther As String
    Public Property ReadByText As String
    Public Property SputumRecommended As Nullable(Of Boolean)
    Public Property SymptomInquiryRecommended As Nullable(Of Boolean)
    Public Property ReadByID As Nullable(Of Integer)

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_GeographicLocation As common_GeographicLocation
    Public Overridable Property common_Clinicians As common_Clinicians
    Public Overridable Property common_GeographicLocation1 As common_GeographicLocation
    Public Overridable Property common_InjectionBodySite As common_InjectionBodySite
    Public Overridable Property common_InjectionRoute As common_InjectionRoute
    Public Overridable Property common_MedicalLot As common_MedicalLot
    Public Overridable Property common_Product As common_Product
    Public Overridable Property common_SkinTestResult As common_SkinTestResult
    Public Overridable Property common_SkinTestSite As common_SkinTestSite
    Public Overridable Property common_Clinicians1 As common_Clinicians
    Public Overridable Property common_TBUser As common_TBUser
    Public Overridable Property common_TBUser1 As common_TBUser
    Public Overridable Property common_TestReason As common_TestReason

End Class
