'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_BCG
    Public Property ID As Integer
    Public Property ClientID As Nullable(Of Integer)
    Public Property StatusID As Nullable(Of Integer)
    Public Property ImmunizationDate As Nullable(Of Date)
    Public Property ImmunizationYear As String

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_YesNoUnknown As common_YesNoUnknown

End Class
