'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Symptoms
    Public Property ID As Integer
    Public Property InterviewByID As Integer
    Public Property InterviewDate As Date
    Public Property ClientID As Integer
    Public Property CompletionMethod As Nullable(Of Integer)
    Public Property Comments As String
    Public Property CoughGreat3Weeks As Nullable(Of Integer)
    Public Property CoughGreat3WeeksNotes As String
    Public Property CoughGreat3WeeksStart As Nullable(Of Date)
    Public Property CoughGreat3WeeksEnd As Nullable(Of Date)
    Public Property ShortnessBreath As Nullable(Of Integer)
    Public Property ShortnessBreathNotes As String
    Public Property ShortnessBreathStart As Nullable(Of Date)
    Public Property ShortnessBreathEnd As Nullable(Of Date)
    Public Property Fever As Nullable(Of Integer)
    Public Property FeverNotes As String
    Public Property FeverStart As Nullable(Of Date)
    Public Property FeverEnd As Nullable(Of Date)
    Public Property NightSweats As Nullable(Of Integer)
    Public Property NightSweatsNotes As String
    Public Property NightSweatsStart As Nullable(Of Date)
    Public Property NightSweatsEnd As Nullable(Of Date)
    Public Property Hemoptysis As Nullable(Of Integer)
    Public Property HemoptysisNotes As String
    Public Property HemoptysisStart As Nullable(Of Date)
    Public Property HemoptysisEnd As Nullable(Of Date)
    Public Property WeightLoss As Nullable(Of Integer)
    Public Property WeightLossNotes As String
    Public Property WeightLossStart As Nullable(Of Date)
    Public Property WeightLossEnd As Nullable(Of Date)
    Public Property LossAppetite As Nullable(Of Integer)
    Public Property LossAppetiteNotes As String
    Public Property LossAppetiteStart As Nullable(Of Date)
    Public Property LossAppetiteEnd As Nullable(Of Date)
    Public Property Fatigue As Nullable(Of Integer)
    Public Property FatigueNotes As String
    Public Property FatigueStart As Nullable(Of Date)
    Public Property FatigueEnd As Nullable(Of Date)
    Public Property Chestpain As Nullable(Of Integer)
    Public Property ChestpainNotes As String
    Public Property ChestpainStart As Nullable(Of Date)
    Public Property ChestpainEnd As Nullable(Of Date)
    Public Property FailureToThrive As Nullable(Of Integer)
    Public Property FailureToThriveNotes As String
    Public Property FailureToThriveStart As Nullable(Of Date)
    Public Property FailureToThriveEnd As Nullable(Of Date)
    Public Property Rash As Nullable(Of Integer)
    Public Property RashEnd As Nullable(Of Date)
    Public Property RashNotes As String
    Public Property RashStart As Nullable(Of Date)

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_CompletionMethod As common_CompletionMethod
    Public Overridable Property common_Clinicians As common_Clinicians
    Public Overridable Property common_YesNoUnknownRefused As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused1 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused2 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused3 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused4 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused5 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused6 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused7 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused8 As common_YesNoUnknownRefused
    Public Overridable Property common_YesNoUnknownRefused9 As common_YesNoUnknownRefused

End Class
