'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Bloodwork
    Public Property ID As Integer
    Public Property CollectedDate As Nullable(Of Date)
    Public Property ResultDate As Nullable(Of Date)
    Public Property CollectionMethodID As Nullable(Of Integer)
    Public Property CollectedBy As Nullable(Of Integer)
    Public Property Alt As String
    Public Property Ast As String
    Public Property SerumBilirubin As String
    Public Property Comments As String
    Public Property ReasonForTestingID As Nullable(Of Integer)
    Public Property ClientID As Nullable(Of Integer)
    Public Property ReasonForTestingOther As String

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_BloodworkCollectionMethod As common_BloodworkCollectionMethod
    Public Overridable Property common_Clinicians As common_Clinicians
    Public Overridable Property common_TestReason As common_TestReason

End Class
