'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_DiagnosticImage
    Public Property ID As Integer
    Public Property ExamDate As Nullable(Of Date)
    Public Property ViewID As Nullable(Of Integer)
    Public Property AreaID As Nullable(Of Integer)
    Public Property IndicationID As Nullable(Of Integer)
    Public Property ResultID As Nullable(Of Integer)
    Public Property Findings As String
    Public Property ClientID As Nullable(Of Integer)
    Public Property ReasonForTesting As Nullable(Of Integer)
    Public Property OtherProcedure As String
    Public Property ReasonForTestingOther As String

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_TestReason As common_TestReason
    Public Overridable Property common_XrayArea As common_XrayArea
    Public Overridable Property common_XrayIndication As common_XrayIndication
    Public Overridable Property common_XrayResult As common_XrayResult
    Public Overridable Property common_XrayView As common_XrayView

End Class
