'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Xray
    Public Property ID As Integer
    Public Property ExamDate As Nullable(Of Date)
    Public Property ViewID As Nullable(Of Integer)
    Public Property AreaID As Nullable(Of Integer)
    Public Property IndicationID As Nullable(Of Integer)
    Public Property ResultID As Nullable(Of Integer)
    Public Property InfiltrateYesNo As Nullable(Of Boolean)
    Public Property InfiltrateYesNoNotes As String
    Public Property CavitaryLession As Nullable(Of Boolean)
    Public Property CavitaryLessionNotes As String
    Public Property Nodule As Nullable(Of Boolean)
    Public Property NoduleNotes As String
    Public Property PleuralEffusion As Nullable(Of Boolean)
    Public Property PleuralEffusionNotes As String
    Public Property HilarLymphadenopathy As Nullable(Of Boolean)
    Public Property HilarLymphadenopathyNotes As String
    Public Property LinearDisease As Nullable(Of Boolean)
    Public Property LinearDiseaseNotes As String
    Public Property Comments As String
    Public Property ReasonForTestingID As Nullable(Of Integer)
    Public Property ReasonForTestingOther As String
    Public Property ClientID As Nullable(Of Integer)

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_TestReason As common_TestReason
    Public Overridable Property common_XrayArea As common_XrayArea
    Public Overridable Property common_XrayIndication As common_XrayIndication
    Public Overridable Property common_XrayResult As common_XrayResult
    Public Overridable Property common_XrayView As common_XrayView

End Class
