'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_Demographic
    Public Property ID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property MiddleInitial As String
    Public Property Alias_MaidenName_Nickname As String
    Public Property SpeaksEN As Nullable(Of Boolean)
    Public Property SpeaksFR As Nullable(Of Boolean)
    Public Property SpeaksInnu As Nullable(Of Boolean)
    Public Property SpeaksInuttitut As Nullable(Of Boolean)
    Public Property HealthCareNumber As String
    Public Property StreetAddress As String
    Public Property Community As String
    Public Property PostalCode As String
    Public Property ProvinceID As Nullable(Of Integer)
    Public Property OtherProvinceStateIdentifier As String
    Public Property RhaEH As Nullable(Of Boolean)
    Public Property RhaCH As Nullable(Of Boolean)
    Public Property RhaWG As Nullable(Of Boolean)
    Public Property RhaLG As Nullable(Of Boolean)
    Public Property RhaOther As Nullable(Of Boolean)
    Public Property RhaOtherText As String
    Public Property MobilePhone As String
    Public Property HomePhone As String
    Public Property OtherPhone As String
    Public Property Email As String
    Public Property DateofBirth As Nullable(Of Date)
    Public Property Occupation As String
    Public Property BodyWeight As Nullable(Of Integer)
    Public Property Comments As String
    Public Property GenderID As Nullable(Of Integer)
    Public Property Active As Boolean
    Public Property ActiveFrom As Nullable(Of Date)
    Public Property ActiveTo As Nullable(Of Date)
    Public Property ClientID As Nullable(Of Integer)
    Public Property PregnancyStatus As Nullable(Of Integer)
    Public Property OtherIdentifier As String
    Public Property EthnicityOther As String
    Public Property CommunityID As Nullable(Of Integer)
    Public Property CaseNumber As String
    Public Property CommunityOther As String

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property common_Community As common_Community
    Public Overridable Property common_PregnancyStatus As common_PregnancyStatus
    Public Overridable Property common_Gender As common_Gender
    Public Overridable Property common_Province As common_Province
    Public Overridable Property common_Ethnicity As ICollection(Of common_Ethnicity) = New HashSet(Of common_Ethnicity)

End Class
