'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client_OutcomeTreatment
    Public Property ID As Integer
    Public Property TreatmentModeID As Nullable(Of Integer)
    Public Property TransferedDestination As String
    Public Property AdherenceID As Nullable(Of Integer)
    Public Property Comments As String
    Public Property OutcomeID As Nullable(Of Integer)
    Public Property ClientDeath As Nullable(Of Boolean)
    Public Property ClientDateDate As Nullable(Of Date)
    Public Property ClientDeathTBCause As Nullable(Of Boolean)
    Public Property ClientDeathTBContribute As Nullable(Of Boolean)
    Public Property ClientDeathTBNoContribute As Nullable(Of Boolean)

    Public Overridable Property client_Outcome As ICollection(Of client_Outcome) = New HashSet(Of client_Outcome)
    Public Overridable Property common_TBOutcome As common_TBOutcome
    Public Overridable Property common_TreatmentAdherence As common_TreatmentAdherence
    Public Overridable Property common_TreatmentMode As common_TreatmentMode
    Public Overridable Property client_OutcomeTreatmentDOT As ICollection(Of client_OutcomeTreatmentDOT) = New HashSet(Of client_OutcomeTreatmentDOT)

End Class
