'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clinic_TBClinicAppointments
    Public Property ID As Integer
    Public Property ClinicID As Nullable(Of Integer)
    Public Property Time As Nullable(Of System.TimeSpan)
    Public Property ClientID As Nullable(Of Integer)
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property Reason As Nullable(Of Integer)
    Public Property ClientType As Nullable(Of Integer)
    Public Property Language As Nullable(Of Integer)
    Public Property Transportation As Nullable(Of Boolean)
    Public Property TaxiNumber As String
    Public Property TaxiPickup As Nullable(Of Boolean)
    Public Property Comments As String
    Public Property Complete As Nullable(Of Boolean)
    Public Property CompletedDate As Nullable(Of Date)
    Public Property CompletedByID As Nullable(Of Integer)

    Public Overridable Property client_Profile As client_Profile
    Public Overridable Property clinic_TBClinic As clinic_TBClinic
    Public Overridable Property common_ClinicReason As common_ClinicReason
    Public Overridable Property common_Language As common_Language
    Public Overridable Property common_TBUser As common_TBUser
    Public Overridable Property common_TBUser1 As common_TBUser

End Class
