'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_TBOutcome
    Public Property ID As Integer
    Public Property TBOutcome As String
    Public Property AssociatedStatus As Nullable(Of Integer)
    Public Property SortOrder As Integer

    Public Overridable Property common_Status As common_Status
    Public Overridable Property client_Outcome As ICollection(Of client_Outcome) = New HashSet(Of client_Outcome)
    Public Overridable Property client_OutcomeTreatment As ICollection(Of client_OutcomeTreatment) = New HashSet(Of client_OutcomeTreatment)

End Class
