'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_TBTypes
    Public Property ID As Integer
    Public Property TBType As String

    Public Overridable Property client_Outcome As ICollection(Of client_Outcome) = New HashSet(Of client_Outcome)

End Class
