'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_YesNoUnknownRefused
    Public Property ID As Integer
    Public Property Value As String
    Public Property Active As Nullable(Of Boolean)

    Public Overridable Property client_RiskFactors As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors1 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors2 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors3 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors4 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors5 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors6 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors7 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors8 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors9 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors10 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors11 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors12 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors13 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors14 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors15 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors16 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors17 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors18 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_Symptoms As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms1 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms2 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms3 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms4 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms5 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms6 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms7 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms8 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_Symptoms9 As ICollection(Of client_Symptoms) = New HashSet(Of client_Symptoms)
    Public Overridable Property client_RiskFactors111 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors131 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors141 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors151 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)
    Public Overridable Property client_RiskFactors161 As ICollection(Of client_RiskFactors) = New HashSet(Of client_RiskFactors)

End Class
