'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_InvestigationType
    Public Property ID As Integer
    Public Property InvestigationType As String

    Public Overridable Property client_Investigation As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)

End Class
