'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_CommunicationResult
    Public Property ID As Integer
    Public Property CommunicationResult As String

    Public Overridable Property client_Communication As ICollection(Of client_Communication) = New HashSet(Of client_Communication)

End Class
