'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_YesNoNotdoneUnknown
    Public Property ID As Integer
    Public Property AnswerText As String

    Public Overridable Property client_Investigation As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_Investigation1 As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_Investigation2 As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_Investigation3 As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_Investigation4 As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_Investigation5 As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)

End Class
