'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_Community
    Public Property ID As Integer
    Public Property Community As String

    Public Overridable Property client_ContactTracing As ICollection(Of client_ContactTracing) = New HashSet(Of client_ContactTracing)
    Public Overridable Property client_Demographic As ICollection(Of client_Demographic) = New HashSet(Of client_Demographic)

End Class
