'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_Antibiotic
    Public Property ID As Integer
    Public Property AntibioticName As String

    Public Overridable Property client_Sputum As ICollection(Of client_Sputum) = New HashSet(Of client_Sputum)

End Class
