'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_BloodworkCollectionMethod
    Public Property ID As Integer
    Public Property CollectionMethod As String

    Public Overridable Property client_Bloodwork As ICollection(Of client_Bloodwork) = New HashSet(Of client_Bloodwork)

End Class
