'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_TBUser
    Public Property UserID As Integer
    Public Property NameLabel As String
    Public Property ClinicianID As Nullable(Of Integer)
    Public Property Active As Boolean
    Public Property AspNetID As String
    Public Property AspNetUserID As Nullable(Of System.Guid)

    Public Overridable Property client_Communication As ICollection(Of client_Communication) = New HashSet(Of client_Communication)
    Public Overridable Property client_Followup As ICollection(Of client_Followup) = New HashSet(Of client_Followup)
    Public Overridable Property client_IGRA As ICollection(Of client_IGRA) = New HashSet(Of client_IGRA)
    Public Overridable Property client_Investigation As ICollection(Of client_Investigation) = New HashSet(Of client_Investigation)
    Public Overridable Property client_SkinTest As ICollection(Of client_SkinTest) = New HashSet(Of client_SkinTest)
    Public Overridable Property client_SkinTest1 As ICollection(Of client_SkinTest) = New HashSet(Of client_SkinTest)
    Public Overridable Property clinic_TBClinic As ICollection(Of clinic_TBClinic) = New HashSet(Of clinic_TBClinic)
    Public Overridable Property clinic_TBClinicAppointments As ICollection(Of clinic_TBClinicAppointments) = New HashSet(Of clinic_TBClinicAppointments)
    Public Overridable Property clinic_TBClinicAppointments1 As ICollection(Of clinic_TBClinicAppointments) = New HashSet(Of clinic_TBClinicAppointments)
    Public Overridable Property common_Clinicians As common_Clinicians

End Class
