'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_YesNoUnknown
    Public Property ID As Integer
    Public Property StrValue As String

    Public Overridable Property client_BCG As ICollection(Of client_BCG) = New HashSet(Of client_BCG)

End Class
