'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_Language
    Public Property ID As Integer
    Public Property Language As String

    Public Overridable Property clinic_TBClinicAppointments As ICollection(Of clinic_TBClinicAppointments) = New HashSet(Of clinic_TBClinicAppointments)

End Class
