'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_TestReasonType
    Public Property ID As Integer
    Public Property ReasonType As String

    Public Overridable Property common_TestReason As ICollection(Of common_TestReason) = New HashSet(Of common_TestReason)

End Class
