'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_TreatmentMode
    Public Property ID As Integer
    Public Property ModeTreatment As String

    Public Overridable Property client_OutcomeTreatment As ICollection(Of client_OutcomeTreatment) = New HashSet(Of client_OutcomeTreatment)

End Class
