'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class common_XrayArea
    Public Property ID As Integer
    Public Property XrayArea As String

    Public Overridable Property client_DiagnosticImage As ICollection(Of client_DiagnosticImage) = New HashSet(Of client_DiagnosticImage)
    Public Overridable Property client_Xray As ICollection(Of client_Xray) = New HashSet(Of client_Xray)

End Class
