'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TBTracingEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TBTracingEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property client_Bloodwork() As DbSet(Of client_Bloodwork)
    Public Overridable Property client_BCG() As DbSet(Of client_BCG)
    Public Overridable Property client_ContactNote() As DbSet(Of client_ContactNote)
    Public Overridable Property client_Demographic() As DbSet(Of client_Demographic)
    Public Overridable Property client_Profile() As DbSet(Of client_Profile)
    Public Overridable Property client_IGRA() As DbSet(Of client_IGRA)
    Public Overridable Property client_Investigation() As DbSet(Of client_Investigation)
    Public Overridable Property client_RiskFactors() As DbSet(Of client_RiskFactors)
    Public Overridable Property client_SkinTest() As DbSet(Of client_SkinTest)
    Public Overridable Property client_Sputum() As DbSet(Of client_Sputum)
    Public Overridable Property client_Symptoms() As DbSet(Of client_Symptoms)
    Public Overridable Property client_Xray() As DbSet(Of client_Xray)
    Public Overridable Property clinic_TBClinic() As DbSet(Of clinic_TBClinic)
    Public Overridable Property clinic_TBClinicAppointments() As DbSet(Of clinic_TBClinicAppointments)
    Public Overridable Property client_DiagnosticImage() As DbSet(Of client_DiagnosticImage)
    Public Overridable Property client_Communication() As DbSet(Of client_Communication)
    Public Overridable Property client_CommunicationBulletin() As DbSet(Of client_CommunicationBulletin)
    Public Overridable Property client_Document() As DbSet(Of client_Document)
    Public Overridable Property client_Followup() As DbSet(Of client_Followup)
    Public Overridable Property client_Notes() As DbSet(Of client_Notes)
    Public Overridable Property client_ContactTracing() As DbSet(Of client_ContactTracing)
    Public Overridable Property common_Antibiotic() As DbSet(Of common_Antibiotic)
    Public Overridable Property common_BloodworkCollectionMethod() As DbSet(Of common_BloodworkCollectionMethod)
    Public Overridable Property common_Clinicians() As DbSet(Of common_Clinicians)
    Public Overridable Property common_ClinicReason() As DbSet(Of common_ClinicReason)
    Public Overridable Property common_CommunicationMethod() As DbSet(Of common_CommunicationMethod)
    Public Overridable Property common_CommunicationReason() As DbSet(Of common_CommunicationReason)
    Public Overridable Property common_CommunicationResult() As DbSet(Of common_CommunicationResult)
    Public Overridable Property common_Community() As DbSet(Of common_Community)
    Public Overridable Property common_CompletionMethod() As DbSet(Of common_CompletionMethod)
    Public Overridable Property common_ContactPriority() As DbSet(Of common_ContactPriority)
    Public Overridable Property common_ContactReason() As DbSet(Of common_ContactReason)
    Public Overridable Property common_ContactType() As DbSet(Of common_ContactType)
    Public Overridable Property common_DocumentType() As DbSet(Of common_DocumentType)
    Public Overridable Property common_Followup() As DbSet(Of common_Followup)
    Public Overridable Property common_Gender() As DbSet(Of common_Gender)
    Public Overridable Property common_GeographicLocation() As DbSet(Of common_GeographicLocation)
    Public Overridable Property common_HivStatus() As DbSet(Of common_HivStatus)
    Public Overridable Property common_IGRAResult() As DbSet(Of common_IGRAResult)
    Public Overridable Property common_InjectionBodySite() As DbSet(Of common_InjectionBodySite)
    Public Overridable Property common_InjectionRoute() As DbSet(Of common_InjectionRoute)
    Public Overridable Property common_InvestigationType() As DbSet(Of common_InvestigationType)
    Public Overridable Property common_Language() As DbSet(Of common_Language)
    Public Overridable Property common_MedicalLot() As DbSet(Of common_MedicalLot)
    Public Overridable Property common_Medication() As DbSet(Of common_Medication)
    Public Overridable Property common_MedicationFrequency() As DbSet(Of common_MedicationFrequency)
    Public Overridable Property common_MedicationStatus() As DbSet(Of common_MedicationStatus)
    Public Overridable Property common_PregnancyStatus() As DbSet(Of common_PregnancyStatus)
    Public Overridable Property common_Product() As DbSet(Of common_Product)
    Public Overridable Property common_Province() As DbSet(Of common_Province)
    Public Overridable Property common_SkinTestResult() As DbSet(Of common_SkinTestResult)
    Public Overridable Property common_SkinTestSite() As DbSet(Of common_SkinTestSite)
    Public Overridable Property common_SputumCultureResult() As DbSet(Of common_SputumCultureResult)
    Public Overridable Property common_SputumRequestBy() As DbSet(Of common_SputumRequestBy)
    Public Overridable Property common_SputumSmearResult() As DbSet(Of common_SputumSmearResult)
    Public Overridable Property common_Status() As DbSet(Of common_Status)
    Public Overridable Property common_Symptoms() As DbSet(Of common_Symptoms)
    Public Overridable Property common_TBOutcome() As DbSet(Of common_TBOutcome)
    Public Overridable Property common_TBTypes() As DbSet(Of common_TBTypes)
    Public Overridable Property common_TBUser() As DbSet(Of common_TBUser)
    Public Overridable Property common_TestReason() As DbSet(Of common_TestReason)
    Public Overridable Property common_TestReasonType() As DbSet(Of common_TestReasonType)
    Public Overridable Property common_TreatmentAdherence() As DbSet(Of common_TreatmentAdherence)
    Public Overridable Property common_TreatmentMode() As DbSet(Of common_TreatmentMode)
    Public Overridable Property common_XrayArea() As DbSet(Of common_XrayArea)
    Public Overridable Property common_XrayIndication() As DbSet(Of common_XrayIndication)
    Public Overridable Property common_XrayResult() As DbSet(Of common_XrayResult)
    Public Overridable Property common_XrayView() As DbSet(Of common_XrayView)
    Public Overridable Property common_YesNoNotdoneUnknown() As DbSet(Of common_YesNoNotdoneUnknown)
    Public Overridable Property common_YesNoUnknown() As DbSet(Of common_YesNoUnknown)
    Public Overridable Property common_YesNoUnknownRefused() As DbSet(Of common_YesNoUnknownRefused)
    Public Overridable Property Audit() As DbSet(Of Audit)
    Public Overridable Property AuditType() As DbSet(Of AuditType)
    Public Overridable Property vwClientList() As DbSet(Of vwClientList)
    Public Overridable Property vwClients() As DbSet(Of vwClients)
    Public Overridable Property vwContactTracingConsolidated() As DbSet(Of vwContactTracingConsolidated)
    Public Overridable Property common_Ethnicity() As DbSet(Of common_Ethnicity)
    Public Overridable Property client_Outcome() As DbSet(Of client_Outcome)
    Public Overridable Property client_OutcomeTreatment() As DbSet(Of client_OutcomeTreatment)
    Public Overridable Property client_OutcomeTreatmentDOT() As DbSet(Of client_OutcomeTreatmentDOT)
    Public Overridable Property client_OutcomeTreatmentRegimen() As DbSet(Of client_OutcomeTreatmentRegimen)
    Public Overridable Property common_ContactRelationship() As DbSet(Of common_ContactRelationship)

End Class
