'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwClientList
    Public Property ID As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property ClientID As Nullable(Of Integer)
    Public Property CaseNumber As String
    Public Property OtherIdentifier As String
    Public Property HealthCareNumber As String
    Public Property ProfileID As Integer
    Public Property DateofBirth As Nullable(Of Date)
    Public Property strDOB As String
    Public Property StatusID As Nullable(Of Integer)
    Public Property Status As String

End Class
