'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwContactTracingConsolidated
    Public Property SourceFirstName As String
    Public Property SourceLastName As String
    Public Property SourceClientID As Nullable(Of Integer)
    Public Property IdentifiedFirstName As String
    Public Property IdentifiedLastName As String
    Public Property IdentifiedClientID As Nullable(Of Integer)
    Public Property ContactType As String
    Public Property ContactTypeID As Nullable(Of Integer)
    Public Property Priority As String
    Public Property PriorityID As Nullable(Of Integer)
    Public Property RelationshipText As String
    Public Property RelationshipID As Nullable(Of Integer)
    Public Property Community As String
    Public Property CommunityID As Nullable(Of Integer)
    Public Property ID As Integer
    Public Property FromDate As Nullable(Of Date)
    Public Property ToDate As Nullable(Of Date)
    Public Property ContactReason As String

End Class
