'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientTabsControl

    '''<summary>
    '''demoLi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents demoLi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkDemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDemo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''symptomsLi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents symptomsLi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSymp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSymp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''skinTestLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents skinTestLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSkinTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSkinTest As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''sputmLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sputmLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSputum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSputum As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''investigationLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investigationLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkInvestigations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkInvestigations As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''diagnosisLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diagnosisLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkDiagnosisTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDiagnosisTreatment As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''treatmentLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents treatmentLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTreatment As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''riskLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents riskLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRiskFactors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRiskFactors As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''communicationLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents communicationLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkCommunication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCommunication As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''contactLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contactLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkContactTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkContactTrace As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''docsLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents docsLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkDocsNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDocsNotes As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''followupLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents followupLI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkFollowUps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFollowUps As Global.System.Web.UI.WebControls.HyperLink
End Class
