'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientDemographic

    '''<summary>
    '''ClientInfoControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientInfoControl As Global.TBTracing.ClientInfoControl

    '''<summary>
    '''ClientTabsControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientTabsControl As Global.TBTracing.ClientTabsControl

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''pnlSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DemographicFormView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DemographicFormView As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''Communities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Communities As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''EthnicDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EthnicDictionary As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''GenderDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenderDictionary As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''PregnancyDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PregnancyDictionary As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''StatusDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDictionary As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''ProvinceDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProvinceDictionary As Global.System.Web.UI.WebControls.EntityDataSource
End Class
