'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DiagnosisHome

    '''<summary>
    '''tbFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFromDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbToDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cblOutcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOutcome As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''cblFiels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblFiels As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''sqlOutcomeTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlOutcomeTypes As Global.System.Web.UI.WebControls.SqlDataSource
End Class
