'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _004a_AddClinic

    '''<summary>
    '''tbClinicDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbClinicDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbEndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbMaxAppointments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMaxAppointments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAdd As Global.System.Web.UI.WebControls.LinkButton
End Class
