'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _007b_skintest_new_Contact

    '''<summary>
    '''tbDatePlaced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDatePlaced As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDateRead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateRead As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbInduration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbInduration As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDateOfConsent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateOfConsent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDOB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdate As Global.System.Web.UI.WebControls.LinkButton
End Class
