'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _009d_investigations_sputum_Contact

    '''<summary>
    '''ClientTabsControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientTabsControl As Global.TBTracing.ClientTabsControl

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''tbCollectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCollectedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbResultDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCompletedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompletedBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRequestedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRequestedBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbRefused control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRefused As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbUnableToProduce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUnableToProduce As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbCollected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCollected As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNotResulted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNotResulted As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbSmearComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSmearComplete As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbPendingCulture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPendingCulture As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbComplete As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''addButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TBUserDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBUserDictionary As Global.System.Web.UI.WebControls.EntityDataSource
End Class
